DeveloperAcademy-POSTECH/MC2-Team2-HomeToGather

- HomeToGather/HomeToGather/Extensions/Color.swift
- Jayden의 custom color를 color extension에 추가함
-
-
-
-
> jayden의 custom color 추가

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/ContentView.swift
- HomeToGather/HomeToGather/Info.plist
- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/Components/SubTitleRow.swift
- HomeToGather/HomeToGather/View/Create/Components/TitleRow.swift
- HomeToGather/HomeToGather/View/Create/First/AdressWebView.swift
- HomeToGather/HomeToGather/View/Create/First/FirstCreateView.swift
- HomeToGather/HomeToGather/View/Create/First/FirstInfo.swift
- HomeToGather/HomeToGather/View/Create/First/SearchAddressButton.swift
- HomeToGather/HomeToGather/View/Create/Second/SecondCreateView.swift
- + 버튼 클릭시 파티 생성 페이지로 이동
- 파티 생성 1번째 페이지 입력 레이아웃
- 날짜 입력
- 웹뷰 구성
- 웹뷰에서 이벤트의 타겟의 value를 가져오는 부분이 blocker
> Create party/add info

- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- 주소 복사시 symbol 변경.
- 주소 복사 function으로 따로 뺌.
> ✨ 주소 복사 수정

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedListView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedListView.swift
- HomeToGather/HomeToGather/View/TicketList/ListTicketView.swift
> [PR] Ticket list/make ticket

- HomeToGather/HomeToGather/Extensions/HideKeyboard.swift
- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/Components/ProgressBar.swift
- HomeToGather/HomeToGather/View/Create/Second/AddListView.swift
- HomeToGather/HomeToGather/View/Create/Second/CostView.swift
- HomeToGather/HomeToGather/View/Create/Second/ExempleView.swift
- HomeToGather/HomeToGather/View/Create/Second/FoodView.swift
- HomeToGather/HomeToGather/View/Create/Second/ListView.swift
- HomeToGather/HomeToGather/View/Create/Second/RuleView.swift
- HomeToGather/HomeToGather/View/Create/Second/SecondCreateView.swift
- 규칙, 음식 입력
- 비용 입력
- 프로그레스바
- xcode버전이 최신버전이 아닌 상태이기 때문에 프로젝트 파일은 제외 함
> Create party/second view

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/Extensions/HideKeyboard.swift
- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/Components/ProgressBar.swift
- HomeToGather/HomeToGather/View/Create/Second/AddListView.swift
- HomeToGather/HomeToGather/View/Create/Second/CostView.swift
- HomeToGather/HomeToGather/View/Create/Second/FoodView.swift
- HomeToGather/HomeToGather/View/Create/Second/ListView.swift
- HomeToGather/HomeToGather/View/Create/Second/RuleView.swift
- HomeToGather/HomeToGather/View/Create/Second/SecondCreateView.swift
- ProgressBar 추가
- CostView 추가
- RuleView, FoodView 추가
- 키보드 비활성화 기능 추가
-
-
> Create party/second progress

- HomeToGather/HomeToGather/View/TicketList/Invited/CardView.swift
- 모달 올라가면 자동으로 keyboard 나타내는 struct 생성.
> ✨: Keyboard 자동으로 보여주기

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedListView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedListView.swift
- HomeToGather/HomeToGather/View/TicketList/ParticipantView.swift
- HomeToGather/HomeToGather/ViewModel/HostedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/InvitedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- 초대된, 주최한 파티 리스트를 파이어베이스에서 가져오는 기능 구현
- 참가자 뷰에서 이름이 긴 경우, truncationMode가 빠져있고, 텍스트 길이 제한이 있던 부분 수정
- 더미 데이터의 경우, 앨리스의 브랜치가 머지되고 삭제할 예정(preview와 함께)
- 본인이 만든 파티가 주최한 파티에서 보이는 버그 발생
> [PR] Ticket list/connection

- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/ParticipantView.swift
- 참여자 이름 표시되는 원 색상 변경 수정.
- 참여자 이름 길이가 원 길이 넘어갈 시에는 말줄임으로 표시되도록 수정.
> Participant list/color change

- HomeToGather/HomeToGather/Extensions/Font/Font.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/FeedbackCardView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/InvitationView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/CardView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/ParticipantView.swift
- 언어 판단 extension 추가.
- Invited / Hosted 파일 내의 Text size 및 언어에 따른 Font 변경.
> ✨: Font 변경

- HomeToGather/HomeToGather/ViewModel/HostedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/InvitedViewModel.swift
- Ticket을 Date(파티 개최 날짜) 내림차순으로 정렬.
> ✨: Ticket 정렬

- HomeToGather/HomeToGather/View/TicketList/ListTicketView.swift
- 파티 리스트에 보일 티켓 구현(다중 해상도 지원)
- outdate된 티켓 구현 예정
> Ticket list/list ticket detail

- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- ViewModel/Feedback 수정
-
-
-
-
> ViewModel/Feedback 수정

- HomeToGather/HomeToGather/View/Create/Share/ShareCardView.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- HomeToGather/HomeToGather/ViewModel/InvitedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- 기타 콘솔 로그 코드 제거
- 버그 수정
-
-
-
-
> 🐛: 머지 과정에서 오류난 PartyColor 코드 수정

- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- correction을 호출할 때 기존 초대장 id를 입력하도록 수정
-
-
-
-
> correction 수정

- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/First/FirstInfo.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- 파티 수정시 새로운 파티로 재생성되는 오류 fix
- 해당 파티의 id 값을 추가로 전달
> 🩹 : 주최한 파티 수정하기 파티 id 추가

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/Extensions/Date.swift
- HomeToGather/HomeToGather/View/TicketList/ListTicketView.swift
- 시간 지난 리스트 티켓 짤려보이는 기능 구현
- 날짜 관련 extension을 Date.swift 파일 생성
> [PR] 시간 지난 리스트 티켓 짤려보이는 기능 구현

- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
-  HostedDetailView와 ModifyView 연결.
- Confirmation Dialog 내부의 '수정하기'를 누르면 ModifyView(Party Data 수정)로 이동.
> ✨: Connect HostedDetailView and ModifyView

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/ContentView.swift
- HomeToGather/HomeToGather/HomeToGatherApp.swift
- HomeToGather/HomeToGather/View/Create/First/FirstInfo.swift
- orientation 모드로 고정
- 날짜 표기 방식 수정
> 🩹 : 가로 기능 막기 및 날짜 표기 변경

- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedListView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedListView.swift
- Ticket 삭제시, HostedTicketList View로 뷰 이동.
- Ticket 삭제시, HostedTIcketList에서 해당 ticket 안보이도록 수정.
> Ticket list v iew/rendering

- HomeToGather/HomeToGather/Extensions/Date.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/ListTicketView.swift
- 날짜 비교 코드 리팩토링
- 이미지 파일명 배열 오타 수정
> [PR] Ticket list/bug fix

- HomeToGather/HomeToGather/View/Create/Components/ProgressBar.swift
- HomeToGather/HomeToGather/View/Create/First/FirstInfo.swift
- HomeToGather/HomeToGather/View/Create/Second/SecondCreateView.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- ProgressBar 애니메이션 추가
- 이전 화면 애니메이션은 미구현
> Create party/progress bar

- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/Second/AddListView.swift
- HomeToGather/HomeToGather/View/Create/Second/FoodView.swift
- HomeToGather/HomeToGather/View/Create/Second/RuleView.swift
- HomeToGather/HomeToGather/View/Create/Second/SecondCreateView.swift
- AddListView 키보드 비활성화시 작성한 내용 등록 기능 추가
> ♻️ : Createparty/AddListView-refactor

- HomeToGather/HomeToGather/Model/Model.swift
- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- HomeToGather/HomeToGather/View/Modify/ColorPickerModifyView.swift
- HomeToGather/HomeToGather/ViewModel/HostedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/InvitedViewModel.swift
- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- PartyData와 Model에서 중복으로 생성되는 id 통일
> ♻️ : id 생성 중복 생성 리팩토링

- HomeToGather/HomeToGather/ContentView.swift
- HomeToGather/HomeToGather/View/Main/MainView.swift
- HomeToGather/HomeToGather/View/Main/ticketView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
> [PR] Bug fix

- HomeToGather/HomeToGather/View/TicketList/Hosted/FeedbackCardView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- Party Description 추가.
- 피드백 배열 처리 방식 변경. (초기 빈 string 삭제.)
> Detail view/description

- HomeToGather/HomeToGather/View/Create/Components/PartyData.swift
- HomeToGather/HomeToGather/View/Modify/ColorPickerModifyView.swift
- HomeToGather/HomeToGather/View/Modify/FirstModifyView.swift
- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
- 파티 수정시 파티 참여자 이름 및 uid 포함해서 전송하도록 수정
> 🐛 : 초대장 수정시 파티 참가자 명단 포함해서 발송하도록 수정

- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedListView.swift
- 주최한 초대장이 없을 경우 생기는 버그 (앱 꺼짐) 버그 수정.
> 🐛:  주최한 초대장 List Bug Fix

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/View/Create/Second/AddListView.swift
- HomeToGather/HomeToGather/View/Create/Second/ExampleButton.swift
- HomeToGather/HomeToGather/View/Create/Second/FoodView.swift
- HomeToGather/HomeToGather/View/Create/Second/RuleView.swift
- example button 터치시 예시 Rule, Food 등록 기능 추가
> ✨: Createparty/add examplebutton

- HomeToGather/HomeToGather/ViewModel/ViewModel.swift
- 초대장을 수정할 때 아이디가 바뀌는 문제 수정
-
-
-
-
> 수정하기 함수 수정

- HomeToGather/HomeToGather/View/TicketList/Hosted/HostedDetailView.swift
> 🐛:  주최자 디테일뷰에서 공유 버그 수정

- HomeToGather/HomeToGather.xcodeproj/project.pbxproj
- HomeToGather/HomeToGather/ContentView.swift
- HomeToGather/HomeToGather/View/TicketList/InvitationView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/CardView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedDetailView.swift
- HomeToGather/HomeToGather/View/TicketList/Invited/InvitedListView.swift
- CardView에서 VStack의 alignment가 안들어간 부분 수정
- 일단 InvitedDetailView에서 Bool 변수를 하나 받도록 수정
- InvitationView 없애도 되나요?
> [PR] 초대된 파티에서 텍스트 정렬, 초대 수락/거절 화면에서 피드백 버튼 버그 수정

- HomeToGather/HomeToGather/ContentView.swift
body: 구현방식 변경에 따라 코드 삭제
- InvitationView삭제로 인한 코드 삭제
-
-
-
-
- [o]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [o]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [o]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [o]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
> :fire: 불필요한 코드 삭제

- HomeToGather/HomeToGather/View/TicketList/Invited/CardView.swift
- HomeToGather/HomeToGather/ViewModel/InvitedViewModel.swift
- 참여/불참 선택하는 뷰에서 버튼의 opacity를 0으로 수정(안보이도록)
- InvitedViewModel에서 참여자가 주최자인지, 이미 있는 참여자인지 확인하는 조건문 작성
- 뷰모델에서 다른 방법이 있으면 그걸로 바꿔주세용
> [PR] Ticket list

- HomeToGather/HomeToGather/View/Main/expanedTicketView.swift
- HomeToGather/HomeToGather/View/Main/ticketView.swift
> 🐛: 티켓 Divider 길이 수정

- HomeToGather/HomeToGather/View/Create/First/FirstInfo.swift
- 주소 검색 웹뷰 주석
- UIKit 에서 value 가져오는 방식 해결 후 활성화 예정
> :recycle: : 주소 검색 주석처리

- HomeToGather/HomeToGather/ContentView.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- HomeToGather/HomeToGather/View/Main/ticketView.swift
- HomeToGather/HomeToGather/View/Modify/ColorPickerModifyView.swift
- 만들기, 수정하기 티켓 뷰 레이아웃 깨짐 수정 (패딩 수정)
- 만들기/수정하기 버튼 반응 영역 수정
-
-
-
> 🐛 : 만들기/수정하기 뷰 레이아웃 깨짐 수정

- HomeToGather/HomeToGather/View/Create/Components/ProgressBar.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorPickerView.swift
- HomeToGather/HomeToGather/View/Create/Third/ColorView.swift
- HomeToGather/HomeToGather/View/Main/ticketView.swift
- TicketView 기기별 화면에 대해 오토레이아웃 적용
- 
-
-
-
> 🐛 Hotfix#1 오토레이아웃 적용
